backend = "glx";
vsync = true;

blur-background = true;
blur-method = "dual_kawase";
blur-strength = 5;

blur-background-exclude = [
     "! (class_g = 'Alacritty' || class_g = 'zen' || class_g = 'Pcmanfm' || class_g = 'pcmanfm')",
    "class_g = 'firefox' && window_type = 'utility'",
    "class_g = 'zen' && window_type = 'utility'"
];

shadow = true;
shadow-radius = 12;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.6;
shadow-exclude = [
    "class_g = 'dwm'",
    "_GTK_FRAME_EXTENTS@:c",
    "class_g = 'File-roller'",
    "class_g = 'zen'",
    "class_g = 'firefox' && window_type = 'utility'",
    "class_g = 'zen' && window_type = 'utility'"
];

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
